name: Build APK (resilient)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 1) Si existe gradlew, dale permisos
      - name: Ensure gradlew is executable (if present)
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            echo "GRADLEW_PRESENT=true" >> $GITHUB_ENV
          else
            echo "GRADLEW_PRESENT=false" >> $GITHUB_ENV
          fi

      # 2) Si NO existe gradlew, configura Gradle y genera el wrapper
      - name: Set up Gradle (only if wrapper missing)
        if: env.GRADLEW_PRESENT == 'false'
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle wrapper (only if wrapper missing)
        if: env.GRADLEW_PRESENT == 'false'
        run: |
          # Usa Gradle global para generar el wrapper con la versión por defecto
          gradle wrapper
          chmod +x ./gradlew

      # 3) Construir el APK usando SIEMPRE el wrapper (ya debería existir)
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk